version: '3'

services:
  untube:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: untube
    ports:
      - "8000:8000"
    volumes:
      - ./db/db.sqlite3:/app/db.sqlite3
